language: node_js
node_js:
  - "iojs"
  - "7"

before_install:
  - npm install gitbook-cli -g
  - npm install gulp-cli -g

install:
  - npm install

script:
  - gitbook build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _book
  on:
    branch: master
