language: node_js
node_js:
- '10'
branches:
  only:
  - master
before_install:
- npm install gitbook-cli -g
install:
- gitbook install
script:
- gitbook build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: _book
  on:
    branch: master
env:
  global:
  - secure: TLjLYPT75Rmv7kQjVukJ2gda6Wtx2lBc6SzEvUd9gQW7fz48VKMKuiq6VBFxdiaQ6Yxbcc2mTWGXENXz0Q5BM+1Q/8oBoCLqUulAsNnwedO1PR8xsNDxUimrl6QkLjJf0BzLA9k369hz+RxZV73OFm6FGFpb6JyclM/Ei33dubjEYOpJ80kkXT6Ueltk/PYyaOK2lAIbbi6PHmeNivoETvNMdsi4jKR1iyvvtU42CkcOL06CsZ67L7Hb+XIqnSPMk7cgJ1AZeYUM5vLjqPuzxg0Wjm42h0mqkmcXXf8k9pqDTlvhutzFPF97wQS0nErnhbqPnjBUhiotQJCMrDLIZdu38ZvTfWHLs5HHBoE25Axa7wRqUAXJGVTc7N1h3uIBkLO47Wd93TvjStnK69a1EW3WHNIOSR14UlElvwPacYdKkhjjxcbU4eZrreL5TSNawd/CF/ADy06gxcq9BkHLbjJbo3HiZ/fOBS730P56Om/7eUR0z4T+tNL9pxJRrbOOtqyJokkV0KmgHO7O7t7QT1hylVvtrBa2geoCzFzZtdHoPMKAtnkE2PQA1pvEq65z2UQgMM4IgylCH9f+5ANfKWdIV4iPKsul3427FjU67yqWBXz/pAnctqEVctqQluxWCXnaXs9aQXC3kw+dpi7Qn2z5dUtSqhblknYfjoQFIPE=
